name: secret_whisperer_token
description: "Action to manage secrets for GitHub Actions workflows using Psono Secret Whisperer."
author: "Joerg Heinrich"

inputs:
  PSONO_API_KEY_ID:
    description: "The API key ID for Psono."
    required: true
  PSONO_API_SECRET_KEY_HEX:
    description: "The API secret key in hexadecimal format for Psono."
    required: true
  PSONO_SERVER_URL:
    description: "The URL of the Psono server."
    required: true
  PSONO_GITHUB_CLI_TOKEN:
    description: "The ID of the GitHub CLI token secret in Psono."
    required: true
outputs:
  REPO_TOKEN:
    description: "The GitHub token retrieved from Psono."
    value: ${{ steps.repo-token-secrets.outputs.secret1 }}

runs:
  using: "composite"
  steps:
    - name: Get Repo Token Secrets
      id: repo-token-secrets
      uses: jfheinrich-eu/psono-secret-whisperer@61fb8cf9ca70b1bf0bf832da4af5d8ae7a665613 # v1.0.0
      with:
        ci_api_key_id: ${{ inputs.PSONO_API_KEY_ID }}
        ci_api_secret_key_hex: ${{ inputs.PSONO_API_SECRET_KEY_HEX }}
        ci_server_url: ${{ inputs.PSONO_SERVER_URL }}
        secret_id: ${{ inputs.PSONO_GITHUB_CLI_TOKEN }}
        secret_type: "secret"
        secret_fields: "password"
        mask_secrets: password
