name: Pull Request Labeler and Description Generator
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types:
      [
        labeled,
        unlabeled,
        opened,
        edited,
        reopened,
        synchronize,
        ready_for_review,
      ]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  generate-pr-description:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Generate the description on the pull request
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: tanmay-pathak/generate-pull-request-description@033c118582de3123bb388d3ec3972ac962dc8b48 # v1.0.0
        id: pr-description
        with:
          pull_request_url: ${{ github.event.pull_request.url }}
          api_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update pull request body
        uses: riskledger/update-pr-description@bb136dcb15789ce886dee9c8e04332c5cbf34832 # v2
        with:
          body: ${{ steps.pr-description.outputs.pull_request_description }}
          token: ${{ secrets.GITHUB_TOKEN }}
